@echo off
echo Cleaning npm cache...
call npm cache clean --force
echo Removing node_modules...
rmdir /s /q node_modules
echo Installing dependencies...
call npm install
echo Installing Supabase packages...
call npm install @supabase/auth-ui-react @supabase/auth-ui-shared @supabase/supabase-js --save